# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

jobs:
- job: A
  steps:
  - script: echo Hello, world!
    displayName: 'Run a one-line script'
   
- job: B
  steps:
  - script: |
     echo Add other tasks to build, test, and deploy your project.
     echo See https://aka.ms/yaml
   displayName: 'R
   
- job: C
  steps:
  - bash: echo "B"
