# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

# Set variables once
variables:
  releaseType: "test"

jobs:
- job: A
  steps:
  - script: echo Hello, world!
    displayName: 'Run a one-line script'

  - script: echo Hello, world!
    displayName: 'Run a one-line script'
    
  - script : echo $(releaseType)
   
- job: B
  steps:
  - script: |
     echo Add other tasks to build, test, and deploy your project.
     echo See https://aka.ms/yaml
  displayName: 'R'
   
- job: C
  steps:
  - bash: echo "B"

  - task: Bash@3
    inputs:
      targetType: 'inline'
      script: |
        # Write your commands here
        
        echo 'Hello world'
      workingDirectory: '/tmp'
      failOnStderr: true
