# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo "public $(public_variable)"
  displayName: 'Run a one-line script'

- script: echo "private $(private_variable)"
  displayName: 'Run a one-line script'

- script: echo $MYENVVAR1
  displayName: 'Run a one-line script'
  env:
    MYENVVAR1: $(private_variable)

- script: |
    $x1 = $MYENVVAR1" xxxxxxxx"
    echo $x1
    echo "a"
  displayName: 'Run a one-line script'
  env:
    MYENVVAR1: $(private_variable)


- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'


